config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  get 'categories/show'
  get '/myaccount', to: 'users#show', as: 'account'
  root to: "pages#landing"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/my_islands', to: "islands#users_islands", as: 'my_islands'
  resources :islands do
    resources :bookings, only: %i[index show create]
    resources :reviews, only: %i[create]
    resources :categories, only: :show
  end
  resources :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :island
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :guests, numericality: { only_integer: true }, inclusion: { in: 1..50, message: 'no more than 50' }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :island_categories
  has_many :islands, through: :island_categories
end

app/models/island.rb
class Island < ApplicationRecord
  has_many_attached :photos
  belongs_to :host, class_name: 'User', foreign_key: :user_id
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :users, through: :bookings
  has_many :island_categories, dependent: :destroy
  has_many :categories, through: :island_categories
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  validates :name, presence: true, uniqueness: true
  validates :location, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/models/island_category.rb
class IslandCategory < ApplicationRecord
  belongs_to :island
  belongs_to :category
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :island
  belongs_to :user
  validates :rating, numericality: { only_integer: true, in: (0..5) }, presence: true
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reviews, dependent: :destroy
  has_many :islands
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # before_action :set_booking, only: %i[index show create]

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @island = Island.find(@booking.island_id)
    @user = current_user
  end

  def create
    @booking = Booking.new(bookings_params)
    @island = Island.find(params[:island_id])
    @booking.island = @island
    @review = Review.new
    @booking.user = current_user
    if @booking.save!
      redirect_to booking_path(@booking)
    else
      render 'islands/show', status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date, :guests)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find[params[:id]]
    @islands = Island.where('category = ?', @category.name)
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  before_action :set_island, only: %i[show edit update destroy]

  def index
    @islands = []
    @markers = []
    if params[:category]
      Island.all.each do |island|
        next unless island.categories.include?(Category.where(name: params[:category])[0])

        @islands << island
        marker = {
                  lat: island.latitude,
                  lng: island.longitude,
                  info_window_html: render_to_string(partial: "map_info", locals: { island: })
                  }
        @markers << marker if island.geocoded?
      end
    else
      @islands = Island.all
      unless @islands.empty?
        @markers = @islands.geocoded.map do |island|
          {
            lat: island.latitude,
            lng: island.longitude,
            info_window_html: render_to_string(partial: "map_info", locals: { island: })
          }
        end
      end
    end
  end

  def show
    @booking = Booking.new
    @island = Island.find(params[:id])
    @review = Review.new
  end

  def new
    @island = Island.new
    @new = true
  end

  def create
    @island = Island.new(island_params)
    @island.host = current_user
    if @island.save
      params[:island][:category_ids].each do |id|
        IslandCategory.create(island_id: @island.id, category_id: id.to_i)
      end
      redirect_to island_path(@island)
    else
      render 'islands/new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @island = Island.find(params[:id])
    if @island.update(island_params)
      params[:island][:category_ids].each do |id|
        IslandCategory.create(island_id: @island.id, category_id: id.to_i)
      end
      redirect_to island_path(@island)
    else
      render :edit, status: :unproccessable_entity
    end
  end

  def destroy
    @island = Island.find(params[:id])
    @island.destroy
    redirect_to root_path, status: :see_other
  end

  def users_islands
    @islands = current_user.islands
    @booked_islands = current_user.bookings.map do |booking|
      booking.island
    end
  end

  private

  def set_island
    @island = Island.find(params[:id])
  end

  def island_params
    params.require(:island).permit(:name, :location, :price, :available, :description, :category_ids, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    @islands = Island.last(4)
  end

  def bookings
    @bookings = current_user.bookings
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @island = Island.find(params[:island_id])
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.island = @island
    @booking = Booking.new
    if @review.save
      redirect_to island_path(@island)
    else
      @review = Review.new
      render 'islands/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @bookings = current_user.bookings.last(4)
    @islands = current_user.islands.last(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_card.html.erb
  <div class="card-container mt-5" id="bookings-card">

    <% carousel = 0 %>

    <% @bookings.each do |booking| %>
    <% island = booking.island %>
      <a href="islands/<%=island.id%>" class='card'>
      <div id="island-card-carousel-<%=carousel_id = carousel += 1 %>" class="carousel slide" data-ride="carousel"  data-interval="false">

        <div class="carousel-inner islands">

          <div class="carousel-item island active">
              <img src="<%= cl_image_path island.photos[0].key %>" class="d-block" alt="island-1">
          </div>
          <div class="carousel-item island">
            <img src="<%= cl_image_path island.photos[1].key %>" class="d-block" alt="island-2">
          </div>
          <div class="carousel-item island">
            <img src="<%= cl_image_path island.photos[2].key %>" class="d-block" alt="island-3">
          </div>

          <div class="carousel-control-prev" href="#island-card-carousel-<%= carousel_id %>" role="button"  data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </div>

          <div class="carousel-control-next" href="#island-card-carousel-<%= carousel_id%>" role="button"  data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </div>

        </div>
      </div>

      <div class="container pt-3" id="card-text">
        <h4><b><%= island.name %></b></h4>
        <p><%= booking.start_date %></p>
        <p><%= booking.end_date %></p>
        <p><%= booking.guests  %> guests</p>
      </div>
    </a>
  <% end %>

</div>

app/views/bookings/index.html.erb
<div class="container">

  <h1>Your Bookings<h1>

  <% if @bookings.empty? %>
    <p>You have no bookings</p>
  <% else %>
    <%= render 'booking_card', locals: { bookings: @bookings } %>
  <% end %>

app/views/bookings/show.html.erb
<div class="container d-flex flex-column align-items-center">
  <div>
    <h1 id="title"> 🏝️ BOOKING DETAILS 🏝️</h1>
  </div>
  <div class="trip-to card" style="width: 50%">
    <h3 class="pt-2">Your trip to: <%= link_to @island.name, island_path(@island), class: "link"%>!</h3>
    <p></p>
    <h5><i class="fa-solid fa-location-dot p-2"></i><%= @island.location %></h5>
  </div>

  <div class="trip-details card trip-card mt-4" style="width: 40%;">
    <p><i class="fa-solid fa-calendar-days" style="padding-top: 15px;"></i>&nbsp;&nbsp;<strong>From:</strong> <%= @booking.start_date.to_fs(:long_ordinal) %></p>
    <p><i class="fa-solid fa-calendar-days"></i>&nbsp;&nbsp;<strong>To:</strong> <%= @booking.end_date.to_fs(:long_ordinal) %></p>
    <p><i class="fa-solid fa-clock"></i>&nbsp;&nbsp;<%=(@booking.end_date - @booking.start_date).to_i %> days&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa-solid fa-users"></i>&nbsp;&nbsp;<%=@booking.guests %> guests</p>
  </div>

  <div class="price-details card mt-4" style="width: 40%;">
  <p></p>
    <% days = (@booking.end_date - @booking.start_date).to_i%>
    <p><i class="fa-solid fa-tag"></i>&nbsp;&nbsp;<strong>Total:</strong> <%= number_to_currency(days * @island.price, unit: "£") %></p>
  </div>

    <div class="button-edit">
     <%= link_to "View my bookings", bookings_path, class: "default-button" %>
    </div>
    <div></div>
    <div class="button-cancel">
     <%= link_to "Cancel my booking", booking_path(@booking), class: "default-button", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to cancel your trip to #{@island.name}?"}%>
    </div>
</div>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>


<% @islands.each do |island| %>
  <%= island.name %>
  <%= island.location %>
  <%= island.price %>
  <%= island.available %>
  <%= island.description %>
<% end %>

app/views/islands/_category_banner.html.erb
<div class="icon-bar mt-3">
    <%= link_to '/islands?category=Accomodates%20Spaceships' do %>
      <i class="fa-solid fa-rocket"></i><br>Accomodates<br>Spaceships
    <% end %>

    <%= link_to '/islands?category=Dragon%20Friendly' do %>
      <i class="fa-solid fa-dragon"></i><br>Dragon<br>Friendly
    <% end %>

    <%= link_to '/islands?category=Local%20Wizard' do %>
      <i class="fa-solid fa-hat-wizard"></i><br>Local<br>Wizard
    <% end %>

    <%= link_to '/islands?category=Local%20Cablecar' do %>
      <i class="fa-solid fa-cable-car"></i><br>Local<br>Cablecar
    <% end %>

    <%= link_to '/islands?category=Secret%20Lair' do %>
      <i class="fa-solid fa-door-open"></i><br>Secret<br>Lair
    <% end %>

    <%= link_to '/islands?category=Secret%20Lair' do %>
      <i class="fa-solid fa-sun"></i><br>Sunshie<br>Guaranteed</a>
    <% end %>

    <%= link_to '/islands?category=Secret%20Lair' do %>
      <i class="fa-solid fa-staff-snake"></i></i><br>Witch<br>Doctor</a>
    <% end %>

    <%= link_to '/islands?category=Secret%20Lair' do %>
      <i class="fa-solid fa-person-skiing"></i></i><br>Ski<br>Resort</a>
    <% end %>

    <%= link_to '/islands?category=Secret%20Lair' do %>
      <i class="fa-solid fa-snowflake"></i></i><br>Ice<br>Caves</a>
    <% end %>
  </div>

app/views/islands/_form.html.erb
<%= simple_form_for(@island) do |f| %>
<div class="mb-4">
    <%= f.label :island_name %>
    <%= f.input :name, as: :string, label:false %>
    <%= f.input :location %>
    <%= f.association :categories, as: :check_boxes %>
    <%= f.label :price_per_night %>
    <%= f.input :price, as: :string, label: false %>
    <%= f.input :description %>
    <% if @new %>
      <%= f.input :photos, as: :file, input_html: {multiple: true} %>
    <% end %>
    <%= f.submit class: "default-button"%>
  <% end %>
</div>

app/views/islands/_form_booking.html.erb
<div class="position-sticky">
  <%= simple_form_for [island, booking] do |f| %>
    <div class="booking-form m-3">
      <h3 id="booking-text" class="p-3 text-center">Book your visit</h3>
      <%= f.input :start_date,
                as: :string,
                input_html: { class: 'm-3 w-100', data: { controller: "datepicker" } } %>
      <%= f.input :end_date,
                as: :string,
                input_html: { class: 'm-3 w-100', data: { controller: "datepicker" } } %>
      <%= f.label :guests %>
      <%= f.input :guests, input_html: {class: "form-control form-control-sm m-3 w-25"},class:"form-control", label: false, placeholder: "3" %>
      <% if current_user %>
        <%= f.submit class: "btn booking-btn m-3" %>
      <% else %>
        <%= link_to 'Log In to Book!', new_user_session_path, class: 'btn booking-btn m-3' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/islands/_map_info.html.erb
<h4><a href='<%= island_path(island)%>%>' style='font-weight: bold'><%= island.name %></a></h4>
<p>£<%= island.price.to_i %> p/n</p>

app/views/islands/_my_islands.html.erb
<div class="card-container mt-3" id="bookings-card"
>
    <% carousel = 0 %>
    <% @islands.each do |island| %>
      <a href="islands/<%=island.id%>" class='card'>
      <div id="island-card-carousel-<%=carousel_id = carousel += 1 %>" class="carousel slide" data-ride="carousel"  data-interval="false">
        <div class="carousel-inner islands">
          <div class="carousel-item island active">
              <img src="<%= cl_image_path island.photos[0].key %>" class="d-block" alt="island-1">
          </div>
          <div class="carousel-item island">
            <img src="<%= cl_image_path island.photos[1].key %>" class="d-block" alt="island-2">
          </div>
          <div class="carousel-item island">
            <img src="<%= cl_image_path island.photos[2].key %>" class="d-block" alt="island-3">
          </div>
          <div class="carousel-control-prev" href="#island-card-carousel-<%= carousel_id %>" role="button"  data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </div>
          <div class="carousel-control-next" href="#island-card-carousel-<%= carousel_id%>" role="button"  data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </div>
        </div>
      </div>
      <div class="container pt-3">
        <h4><b><%= island.name %></b></h4>
        <p><%= island.location %></p>
        <p>£<%= island.price.to_i %> p/n</p>
      </div>
      </a>
    <% end %>
  </div>

app/views/islands/edit.html.erb
<div class="container">
  <h1> 🏝️ Update your Island 🏝️</h1>
  <%=render "form", island: @island%>
</div>

app/views/islands/new.html.erb
<div class="container">
  <h1> 🏝️ Add your Island 🏝️</h1>
  <%=render "form", island: @island%>
</div>

app/views/islands/show.html.erb
<%# TODO %>
<%# - Continue customising review cards %>
<%# - Add category icons to show page %>
<%# - Once added, we need to have it so ONLY the icons  %>
<%# - That fit for the island show up %>

<style>
#island-card-carousel-show{
  width: 100vw;
  position: relative;
  left: 50%;
  right: 50%;
  margin-left: -50vw;
  margin-right: -50vw;

#book-form-sticky {
  position: sticky;
  top: 0;
}

img{
  width: 100%;
  object-fit: center;
}

</style>

<div class="island-card container justify-content-center">


  <div class="row">
    <div class="col-md-12 mb-4 img-card">

      <%# HEADER %>

      <h1 data-controller="typed" class="island-hub" data-typed-sentences-value="<%= [@island.name].to_json %>"></h1>
      <h2 class="text-center" data-controller="typed" data-typed-sentences-value="<%= [@island.location].to_json %>"></h2>


    <%# EDIT BUTTON FOR ISLAND HOST %>
      <% if current_user == @island.host %>
        <div class="show-page-btns d-flex justify-content-end gap-3">
          <div class="btn edit-btn"><%= link_to "Edit #{@island.name}", edit_island_path, class:"text-light" %></div>
        </div>
      <%end%>

    <%# REVIEW COUNT %>
      <p>⭐
        <%=
          if @island.reviews.count > 0
            total_rating = @island.reviews.sum(:rating)
            average_rating = (total_rating.to_f / @island.reviews.count).round(1)
          else
            ''
          end
        %>
        <u><a class="review-a" href="#reviews-section"><%= @island.reviews.count %> reviews</a></u>
        </p>
    </div>
  </div>
    <%# ISLAND CAROUSEL %>

      <div id="island-card-carousel-show" class="carousel slide" data-ride="carousel"  data-interval="false">
        <div class="carousel-inner">
        <% if @island.photos.length >= 3 %>
          <div class="carousel-item active c-item">
            <img src="<%= cl_image_path @island.photos[0].key %>" class="d-block w-100 c-img" alt="...">
          </div>
          <div class="carousel-item c-item">
            <img src="<%= cl_image_path @island.photos[1].key %>" alt="...">
          </div>
          <div class="carousel-item c-item">
            <img src="<%= cl_image_path @island.photos[2].key %>" alt="...">
          </div>
        <% else %>
          <div class="carousel-item active c-item">
            <img src="<%= image_path "island_demo1"%>" class="d-block w-100" alt="island-1">
          </div>
          <div class="carousel-item c-item">
            <img src="<%= image_path "island_demo2"%>" class="d-block w-100" alt="island-1">
          </div>
          <div class="carousel-item c-item">
            <img src="<%= image_path "island_demo3"%>" class="d-block w-100" alt="island-1">
          </div>
        <% end %>
          <button class="carousel-control-prev" type="button" data-bs-target="#island-card-carousel-show" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#island-card-carousel-show" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
            </button>
        </div>
      </div>

    </div>


<div class="island-card container justify-content-center">

<%# DETAILS CARD  %>
  <div class="row mb-3 gx-5 mt-4 position-relative">

    <div class="col-md-6 mb-4 details-card">

      <div class="d-flex justify-content-between show-categories">
        <h3 class="px-4">Details</h3>
          <%# CATEGORIES ICONS GO HERE %>
        <div >
          <% @island.categories.each do |category| %>
          <%= category.icon.html_safe %>
          <% end %>
        </div>
      </div>


      <%# CARD CONTENT %>
      <div class="rounded p-3">
        <div class="island-details border-top mb-3">
          <div><i class="fa-solid fa-earth-americas p-2"></i><%= @island.name %></div>
          <div><i class="fa-solid fa-location-dot p-2"></i><%= @island.location %></div>
          <div><i class="fa-solid fa-credit-card p-2"></i>£<%= @island.price.round(2) %></div>
          <div class="border-top mt-3 mb-3"><i class="fa-solid fa-circle-info p-2"></i></div>
          <div class="p-2 fs-5 island-description"><%= @island.description %></div>
          <div class="mb-3 fs-6 p-2"><u>Show more</u> &gt;</div>
        </div>
      </div>


      <% if current_user && !current_user.bookings.where(island_id: @island.id).empty? %>
        <div class="border-top border-3"></div>
        <div class="row mb-3 gx-5 d-flex justify-content-start">
          <div class="col-md-6 mb-4 add-review-form">
            <%# Review Form! %>
            <div class="">
              <%# <h3>Review form</h3> %>
              <div class="mb-4"></div>
              <h3 class="m-3">How was your trip to <strong><%= @island.name %>?</strong> </h3>
              <p class="m-3">We value <u>your</u> feedback!</p>
              <%# Form content %>
              <%= render 'reviews/new_review'%>
            </div>
          </div>
        </div>
      <% end %>
    </div>


    <div class="col-md-6 mb-4 booking-container align-self-start top-0 end-0">
      <%# Booking Form! %>
      <div id='book-form-sticky'>
        <%# Form content %>
        <%= render partial: "islands/form_booking", locals: {booking: @booking, island: @island} %>
      </div>
    </div>

  </div>


      <div class="row mb-3 gx-5 border-top border-2">
        <div class="col-md-6 mb-4 reviews-card w-100">

          <% if @island.reviews.count > 0 %>
            <br>
            <div class="mt-4 mb-4">
              <h4><i class="fa-solid fa-star p-2"></i><%= average_rating %> - <%=@island.reviews.count%> Reviews</h4>
            </div>
            <%# Reviews Card! %>
            <div>
              <%# Reviews content %>
              <div class="row justify-content-center g-5 reviews-row" id="reviews-section">
                <% @island.reviews.each do |review| %>
                  <div class="col-md-4 text-center review-card">
                    <p>
                      <img class="avatar d-flex justify-content-start" alt="avatar"
                        src="https://media.istockphoto.com/id/1298261537/vector/blank-man-profile-head-icon-placeholder.jpg?s=612x612&w=0&k=20&c=CeT1RVWZzQDay4t54ookMaFsdi7ZHVFg2Y5v7hxigCA="
                      />
                    </p>
                    <i class="fa-solid fa-quote-left"></i>
                    <p class="fs-6"><em><%= review.content %></em></p>
                    <i class="fa-solid fa-quote-right"></i>
                    <p class="mt-2"><%= '⭐' * review.rating %></p>
                    <% if review.rating >= 1 && review.rating <= 2 %>
                      <p class="fs-2 d-flex justify-content-end rating-emoji">🙁</p>
                    <% elsif review.rating >= 3 && review.rating <= 4 %>
                      <p class="fs-2 d-flex justify-content-end rating-emoji">🙂</p>
                    <% elsif review.rating == 5 %>
                      <p class="fs-2 d-flex justify-content-end rating-emoji">😁</p>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          <% else %>
            <h4 class="mt-5 text-center">No reviews just yet!</h4>
          <% end %>
        </div>
      </div>

      <%# DELETE BUTTON FOR ISLAND HOST %>
      <%if current_user == @island.host%>
        <div class="d-flex justify-content-center mt-5 mb-5">
          <div class="btn btn-danger delete-btn"><%= link_to "Delete #{@island.name}", island_path, class:"text-light", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{@island.name}?"}%></div>
        </div>
      <%end%>

</div>

app/views/islands/users_islands.html.erb
<div class="container">
  <h2>Islands I own</h2>
  <%= render 'my_islands', locals: {islands: @islands} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateIslandRental</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;600&family=Montserrat:wght@200&family=Noto+Sans:ital,wght@0,200;0,600;1,300&family=Source+Sans+Pro:wght@200&display=swap" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_flashes.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon"
    data-controller="navbar-background" data-action="scroll@window->navbar-background#fire">
  <div class="container-fluid">

    <div>
      <%= link_to "/islands", class: "navbar-brand" do %>
        <%= image_tag "island_icon.png" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

        <div class="profile-navbar">
          <div>
            <li class="nav-item">
              <%= link_to new_island_path, class: "nav-link" do %>
                  <button class=" default-button mx-1">Add An Island</button>
                <% end %>
            </li>
          </div>

        <div>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://static01.nyt.com/images/2021/02/21/arts/21rock-triptych/21rock-triptych-mediumSquareAt3X.jpg", class: "avatar", alt: "dropdown menu" %>
          </a>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", users_show_path, class: "dropdown-item" %>
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "My Islands", my_islands_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>

          </li>

            <% else %>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </div>
        </div>

      </ul>
    </div>
  </div>
</div>